# Generated by Django 3.1.1 on 2020-09-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.IntegerField(choices=[(1, 'icon'), (2, 'text'), (3, 'check')], default=2),
        ),
    ]
