# Generated by Django 3.1.1 on 2020-09-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200908_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('show_section', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
