# Generated by Django 3.1.1 on 2020-09-15 04:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200914_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background_secondary_color',
            field=colorfield.fields.ColorField(default='#343a40', max_length=18),
        ),
    ]
