# Generated by Django 3.1.1 on 2020-09-15 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
